# Generated by Django 5.0.2 on 2024-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.TextField()),
                ('airline_code', models.CharField(max_length=4)),
                ('flight_number', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('travel_class', models.CharField(blank=True, max_length=20, null=True)),
                ('seats_available', models.IntegerField(blank=True, null=True)),
                ('base_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
